import SwiftUI
import WingmanCore

private enum NIMConnectionStatus: Equatable {
  case untested
  case testing
  case success
  case failure(String)
}

struct SettingsView: View {
  @Bindable var model: AppModel
  @State private var confirmErase = false
  @State private var nimStatus: NIMConnectionStatus = .untested

  private let nimClient = NIMClient()

  var body: some View {
    ScrollView(showsIndicators: false) {
      VStack(alignment: .leading, spacing: 16) {
        EditorialHeader(
          rubric: "Privacy",
          title: "Nothing sends itself."
        )
        .padding(.bottom, 4)

        memoriesLink
        privacyContract
        nimSection
        syncSection
        historySection
        prototypeSection
        eraseSection
      }
      .padding(.horizontal, 20)
      .padding(.top, 10)
      .padding(.bottom, 32)
    }
    .editorialPage()
    .toolbar(.hidden, for: .navigationBar)
    .confirmationDialog(
      "Erase all Wingman data?",
      isPresented: $confirmErase,
      titleVisibility: .visible
    ) {
      Button("Erase Wingman data", role: .destructive) { model.eraseWingmanData() }
      Button("Cancel", role: .cancel) {}
    }
  }

  // MARK: - Memories

  /// Memories lost its tab to Connections. It belongs here rather than nowhere:
  /// the writing style, the remembered facts, and the Mac graph import are all
  /// data controls, which is what this page is.
  private var memoriesLink: some View {
    NavigationLink {
      MemoriesView(model: model)
    } label: {
      HStack(spacing: 13) {
        Image(systemName: "star")
          .font(.system(size: 17))
          .foregroundStyle(WingmanEditorial.accent)

        VStack(alignment: .leading, spacing: 4) {
          Text("What Wingman remembers")
            .font(WingmanEditorial.heading())
            .foregroundStyle(WingmanEditorial.ink)
          Text("Your writing style, your memories, and the Mac graph import.")
            .font(WingmanEditorial.body(13))
            .foregroundStyle(WingmanEditorial.inkSecondary)
            .fixedSize(horizontal: false, vertical: true)
            .multilineTextAlignment(.leading)
        }

        Spacer(minLength: 0)

        Image(systemName: "chevron.right")
          .font(.system(size: 13, weight: .medium))
          .foregroundStyle(WingmanEditorial.inkSecondary.opacity(0.6))
      }
      .editorialCard(padding: 18)
    }
    .buttonStyle(.plain)
  }

  // MARK: - The contract

  private var privacyContract: some View {
    VStack(alignment: .leading, spacing: 16) {
      EditorialRubric("The contract")

      EditorialAttributeRow(
        "eye.slash",
        "No transcript access on iPhone",
        detail: "Only text you paste or share is used in the extension."
      )
      EditorialDivider()
      EditorialAttributeRow(
        "hand.raised",
        "You approve profile fields",
        detail: "Unapproved fields never enter matching or introduction cards."
      )
      EditorialDivider()
      EditorialAttributeRow(
        "paperplane",
        "You tap Send",
        detail: "Wingman inserts drafts into Messages and never sends autonomously."
      )
    }
    .editorialCard(padding: 20)
  }

  // MARK: - NIM

  private var nimSection: some View {
    VStack(alignment: .leading, spacing: 14) {
      HStack {
        EditorialRubric("NVIDIA NIM")
        Spacer()
        StatusMark(
          text: nimClient.hasAPIKey ? "Key found" : "Missing key",
          ok: nimClient.hasAPIKey
        )
      }

      Text("Drafts are generated by NVIDIA NIM using your writing style and memories. If a request fails, Wingman falls back to offline template drafts automatically.")
        .font(WingmanEditorial.body(13))
        .foregroundStyle(WingmanEditorial.inkSecondary)
        .fixedSize(horizontal: false, vertical: true)

      if case .failure(let message) = nimStatus {
        Text(message)
          .font(WingmanEditorial.body(13))
          .foregroundStyle(WingmanEditorial.accent)
          .fixedSize(horizontal: false, vertical: true)
      }

      Button {
        Task { await testNIMConnection() }
      } label: {
        switch nimStatus {
        case .testing: Text("Testing…")
        case .success: Label("Connected", systemImage: "checkmark")
        case .failure: Text("Retry test")
        case .untested: Text("Test NIM connection")
        }
      }
      .buttonStyle(.editorialSecondary)
      .disabled(nimStatus == .testing || !nimClient.hasAPIKey)
      .opacity(nimClient.hasAPIKey ? 1 : 0.4)
    }
    .editorialCard(padding: 20)
  }

  // MARK: - Sync

  private var syncSection: some View {
    VStack(alignment: .leading, spacing: 14) {
      HStack {
        EditorialRubric("Prototype profile sync")
        Spacer()
        StatusMark(
          text: model.syncIsConfigured ? "Configured" : "Missing URL",
          ok: model.syncIsConfigured
        )
      }

      Text("Wingman uploads only fields approved for matching, then downloads the other approved profiles in the prototype database. Set WINGMAN_SYNC_BASE_URL in Secrets.xcconfig before building a device app.")
        .font(WingmanEditorial.body(13))
        .foregroundStyle(WingmanEditorial.inkSecondary)
        .fixedSize(horizontal: false, vertical: true)

      if let lastProfileSyncAt = model.lastProfileSyncAt {
        Text("Last synced \(lastProfileSyncAt, format: .dateTime.hour().minute().second())")
          .font(WingmanEditorial.body(12))
          .foregroundStyle(WingmanEditorial.inkSecondary)
      }

      Button {
        model.syncProfiles()
      } label: {
        Text(model.isSyncingProfiles ? "Syncing profiles…" : "Sync approved profile")
      }
      .buttonStyle(.editorialSecondary)
      .disabled(model.isSyncingProfiles || !model.syncIsConfigured)
      .opacity(model.syncIsConfigured ? 1 : 0.4)
    }
    .editorialCard(padding: 20)
  }

  // MARK: - History bridge

  private var historySection: some View {
    VStack(alignment: .leading, spacing: 16) {
      EditorialRubric("History bridge")

      EditorialAttributeRow("desktopcomputer", "Mac watcher", detail: "Runs on your Mac")
      EditorialDivider()
      EditorialAttributeRow("iphone", "iPhone history sync", detail: "Separate future feature")

      Text("The profile gateway does not upload Messages history. The optional Mac history bridge remains local until it has a reviewed, encrypted context transport.")
        .font(WingmanEditorial.body(13))
        .foregroundStyle(WingmanEditorial.inkSecondary)
        .fixedSize(horizontal: false, vertical: true)
    }
    .editorialCard(padding: 20)
  }

  // MARK: - Prototype facts

  private var prototypeSection: some View {
    VStack(alignment: .leading, spacing: 14) {
      EditorialRubric("Prototype")

      FactRow(label: "Profile", value: model.profileReady ? "Ready" : "Incomplete")
      EditorialDivider()
      FactRow(label: "Invited humans", value: "\(model.candidateCount)")
      EditorialDivider()
      FactRow(label: "Data schema", value: "v\(WingmanState.schemaVersion)")
    }
    .editorialCard(padding: 20)
  }

  // MARK: - Erase

  private var eraseSection: some View {
    VStack(alignment: .leading, spacing: 12) {
      Text("This deletes Wingman’s local profile, candidates, insights, and approvals. It never alters Messages history.")
        .font(WingmanEditorial.body(13))
        .foregroundStyle(WingmanEditorial.inkSecondary)
        .fixedSize(horizontal: false, vertical: true)

      Button(role: .destructive) {
        confirmErase = true
      } label: {
        Text("Erase all Wingman data")
          .font(.system(size: 15, weight: .semibold))
          .foregroundStyle(WingmanPalette.danger)
          .frame(maxWidth: .infinity)
          .padding(.vertical, 13)
          .overlay(Capsule().stroke(WingmanPalette.danger.opacity(0.4), lineWidth: 1))
      }
      .buttonStyle(.plain)
    }
    .editorialCard(padding: 20)
  }

  private func testNIMConnection() async {
    nimStatus = .testing
    do {
      _ = try await nimClient.complete(system: "Reply with one word.", user: "Say ok.", maxTokens: 5)
      nimStatus = .success
    } catch {
      nimStatus = .failure(error.localizedDescription)
    }
  }
}

/// A configured/missing mark. Deliberately not a green or amber dot — on this
/// surface the accent means "good to go" and plain ink means "not yet",
/// keeping the page to one color.
private struct StatusMark: View {
  let text: String
  let ok: Bool

  var body: some View {
    Text(text)
      .font(WingmanEditorial.body(12, .medium))
      .foregroundStyle(ok ? WingmanEditorial.accent : WingmanEditorial.inkSecondary)
      .padding(.horizontal, 10)
      .padding(.vertical, 4)
      .overlay(
        Capsule().stroke(
          ok ? WingmanEditorial.accent.opacity(0.3) : WingmanEditorial.hairline,
          lineWidth: 1
        )
      )
  }
}

private struct FactRow: View {
  let label: String
  let value: String

  var body: some View {
    HStack {
      Text(label)
        .font(WingmanEditorial.body(15))
        .foregroundStyle(WingmanEditorial.ink)
      Spacer()
      Text(value)
        .font(WingmanEditorial.body(15))
        .foregroundStyle(WingmanEditorial.inkSecondary)
    }
  }
}
