import SwiftUI
import WingmanCore

private enum NIMConnectionStatus: Equatable {
  case untested
  case testing
  case success
  case failure(String)
}

struct SettingsView: View {
  @Bindable var model: AppModel
  @State private var confirmErase = false
  @State private var nimStatus: NIMConnectionStatus = .untested

  private let nimClient = NIMClient()

  var body: some View {
    VStack(spacing: 0) {
      PrivacyBadge()
        .padding(.top, WingmanMetrics.Spacing.sm)
        .padding(.bottom, WingmanMetrics.Spacing.xs)

      settingsList
    }
    .navigationTitle("Privacy")
    .confirmationDialog(
      "Erase all Wingman data?",
      isPresented: $confirmErase,
      titleVisibility: .visible
    ) {
      Button("Erase Wingman data", role: .destructive) { model.eraseWingmanData() }
      Button("Cancel", role: .cancel) {}
    }
  }

  private var settingsList: some View {
    List {
      Section("Privacy contract") {
        PrivacyRow(icon: "eye.slash.fill", title: "No transcript access on iPhone", detail: "Only text you paste or share is used in the extension.")
        PrivacyRow(icon: "hand.raised.fill", title: "You approve profile fields", detail: "Unapproved fields never enter matching or introduction cards.")
        PrivacyRow(icon: "paperplane.fill", title: "You tap Send", detail: "Wingman inserts drafts into Messages and never sends autonomously.")
      }

      Section {
        LabeledContent("API key") {
          Text(nimClient.hasAPIKey ? "Found in bundle" : "Missing — add Secrets.xcconfig")
            .foregroundStyle(nimClient.hasAPIKey ? WingmanPalette.success : WingmanPalette.warning)
        }
        Button {
          Task { await testNIMConnection() }
        } label: {
          switch nimStatus {
          case .testing:
            Label("Testing…", systemImage: "hourglass")
          case .success:
            Label("Connected", systemImage: "checkmark.circle.fill")
          case .failure:
            Label("Retry test", systemImage: "arrow.clockwise")
          case .untested:
            Label("Test NIM connection", systemImage: "bolt.horizontal.circle")
          }
        }
        .disabled(nimStatus == .testing || !nimClient.hasAPIKey)
        if case .failure(let message) = nimStatus {
          Text(message)
            .font(WingmanType.caption())
            .foregroundStyle(WingmanPalette.warning)
        }
      } header: {
        Text("NVIDIA NIM")
      } footer: {
        Text("Drafts are generated by NVIDIA NIM using your writing style and memories. If a request fails, Wingman falls back to offline template drafts automatically.")
      }

      Section {
        LabeledContent("Mac watcher") {
          Text("Runs on your Mac")
            .foregroundStyle(WingmanPalette.inkSecondary)
        }
        LabeledContent("iPhone sync") {
          Text("Not built yet")
            .foregroundStyle(WingmanPalette.warning)
        }
        Text("Install the `wingman-history` watch daemon on your Mac (see the README) to have Wingman automatically notice new Messages as they arrive, entirely on that Mac. There is no way for an iPhone app to read your Messages history directly — Apple doesn't allow it. Getting the Mac's derived context onto your iPhone automatically is the next milestone and isn't wired up yet.")
          .font(WingmanType.caption())
          .foregroundStyle(WingmanPalette.inkSecondary)
      } header: {
        Text("History bridge")
      }

      Section("Prototype") {
        LabeledContent("Profile", value: model.profileReady ? "Ready" : "Incomplete")
        LabeledContent("Invited humans", value: "\(model.candidateCount)")
        LabeledContent("Data schema", value: "v\(WingmanState.schemaVersion)")
      }

      Section {
        Button("Erase all Wingman data", role: .destructive) {
          confirmErase = true
        }
      } footer: {
        Text("This deletes Wingman’s local profile, candidates, insights, and approvals. It never alters Messages history.")
      }
    }
  }

  private func testNIMConnection() async {
    nimStatus = .testing
    do {
      _ = try await nimClient.complete(system: "Reply with one word.", user: "Say ok.", maxTokens: 5)
      nimStatus = .success
    } catch {
      nimStatus = .failure(error.localizedDescription)
    }
  }
}

private struct PrivacyRow: View {
  let icon: String
  let title: String
  let detail: String

  var body: some View {
    HStack(alignment: .top, spacing: WingmanMetrics.Spacing.sm) {
      Image(systemName: icon)
        .foregroundStyle(WingmanPalette.accent)
        .frame(width: 24)
      VStack(alignment: .leading, spacing: 3) {
        Text(title).font(WingmanType.headline())
        Text(detail).font(WingmanType.caption()).foregroundStyle(WingmanPalette.inkSecondary)
      }
    }
    .padding(.vertical, 3)
  }
}
